### ISSUE TITLE
Request: remove the welcome message

### ISSUE THREAD

**Issue by 07416** [reveddit/reveddit#5]
![2020-01-21 10_27_58-Window](https://user-images.githubusercontent.com/14923168/72787514-c3db8480-3c38-11ea-81e9-3976580c3084.png)

The pop-up element appears essentially each time when accessing Revddit, as I prefer clearing cookies on browser shutdown. I feel that the message has served its purpose and should be less obstructive.

I would move a notification to the `header` page element.

**Comment by rhaksw** [comment]
Hi, I made a change that should fix things for you. Now there is a slight delay before showing the overlay message, so the extension can tell the website it is installed. If you have the extension then the message will not appear. Otherwise, a workaround is browsing via a private session. I'm probably going to keep some sort of one-time notice around for the time being.
