### ISSUE TITLE
false positives. approved comments are not detected

### ISSUE THREAD

**Issue by milahu** [reveddit/reveddit#7]
https://www.reveddit.com/y/milahu/?sort=top&all=true&showFilters=true&removedby=anti_evil_ops%2Cmod%2Cunknown%2Cautomod

shows many `[removed] unknown if by mod/automod` comments
but most or all of these comments were approved

**Comment by rhaksw** [comment]
Hi, these are all removed. The link in the blue box at the top of the page will show it,

> Some comments have been removed. To view this on reddit, open the below link in an incognito window or while logged out.
> [view removed comments on reddit](https://www.reddit.com/api/info?id=t1_h9n08ub,t1_h9n055t,t1_h9kai0c,t1_h9ka3ez,t1_h95obsn,t1_h8ohzi7,t1_h7nuq94,t1_h3ggm1j,t1_h1zgxs6,t1_gu9ia5w,t1_gu9h3c3,t1_gu4zpg2,t1_gttxbuc,t1_gtg3o9p,t1_gs30wnb,t1_gqy1kke,t1_gqu194t,t1_gqspjrh)

You can open that link while logged out or with incognito mode or a private session. They all [say [removed]](https://i.imgur.com/mT82Ek8.png).

The comments [from the quarantined subreddit](https://www.reddit.com/api/info?id=t1_h9n08ub,t1_h9n055t,t1_h9kai0c,t1_h9ka3ez,t1_h95obsn,t1_h8ohzi7,t1_h7nuq94,t1_h3ggm1j,t1_h1zgxs6,t1_gu9ia5w,t1_gu9h3c3,t1_gu4zpg2,t1_gttxbuc,t1_gtg3o9p,t1_gs30wnb,t1_gqy1kke,t1_gqu194t,t1_gqspjrh) will not show up. That's because [reddit's API does not return quarantined content for unauthenticated users](https://www.reddit.com/r/redditdev/comments/3fx3gt/quarantined_content_will_be_unavailable_through/). So to verify those you would need to use another account. Reveddit is able to show these as removed on user pages by relaying client requests with serverless functions.

**Comment by milahu** [comment]
aah, so reddit is [shadowbanning](https://techcrunch.com/2015/11/11/reddit-account-suspensions/). thanks to clarify
