### ISSUE TITLE
Bookmark bar button

### ISSUE THREAD

**Issue by minhngoc25a** [reveddit/reveddit#9]
Reveddit is based on the source code of removeddit. The latter site had something that I really liked. A bookmark bar script to view current Reddit post in Reveddit.

For example, this link: https://www.reddit.com/r/relationship_advice/comments/sila06/my_38f_husband_37m_drunkenly_admitted_he_only/

And with the code `javascript: document.location = document.URL.replace('reddit.com','reveddit.com');`, I can do that and transform it to: https://www.reveddit.com/v/relationship_advice/comments/sila06/my_38f_husband_37m_drunkenly_admitted_he_only/

The homepage of Removeddit had that link, and it can be dragged to the bookmark bar to save it. It is quite a convenient feature and it would be nice to have it in Reveddit's homepage as well.

**Comment by rhaksw** [comment]
Hi, thanks for writing. I put it back in [the FAQ](https://www.reveddit.com/about/faq/#linker-extension) and on the add-ons page.

I had removed this because the [Linker extension](https://www.reveddit.com/add-ons/linker) does more. That one adds [a button](https://i.imgur.com/0BAImPq.png) directly onto comments, posts, and contextual menus.
